'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {lessons,subjects,subjectName,materials,monitors} from '@/lib/content';
import type {Progress} from '@/lib/progress';
import {QuestionCard} from './training';
export function Study({progress,update,initialLesson}:{progress:Progress;update:(p:Progress)=>void;initialLesson?:string}){
 const [subject,setSubject]=useState(''),[search,setSearch]=useState(''),[lessonId,setLesson]=useState(initialLesson||'');
 const lesson=lessons.find(l=>l.id===lessonId);const filtered=lessons.filter(l=>(!subject||l.subject===subject)&&(l.title+' '+l.text.join(' ')).toLocaleLowerCase('pt-BR').includes(search.toLocaleLowerCase('pt-BR')));
 if(lesson)return <article className="reading"><Button variant="ghost" onClick={()=>setLesson('')}><ArrowLeft size={16}/> Voltar aos assuntos</Button><p className="eyebrow">{subjectName(lesson.subject)} · II trimestre</p><h1>{lesson.title}</h1><p className="lead">Ao terminar, tente explicar o assunto com suas palavras e resolver a questão sem consultar.</p><div className="reading-body">{lesson.text.map((p,i)=><p key={i}>{p}</p>)}<aside className="worked"><span className="eyebrow">NA PRÁTICA</span><h2>Ligando as ideias</h2><p>{lesson.example}</p></aside><div className="attention"><strong>Um cuidado importante</strong><p>{lesson.trap}</p></div><h2>Confira se entendeu</h2><QuestionCard key={lesson.id} question={{...lesson,id:`lesson-${lesson.id}`,source:'Questão autoral de revisão'}} selected={progress.answers[`lesson-${lesson.id}`]} onAnswer={a=>update({...progress,answers:{...progress.answers,[`lesson-${lesson.id}`]:a}})}/><label className="checkline"><input type="checkbox" checked={!!progress.read[lesson.id]} onChange={e=>update({...progress,read:{...progress.read,[lesson.id]:e.target.checked},lastLesson:lesson.id})}/> Consigo explicar este assunto</label><label htmlFor="lesson-notes"><h2>Suas anotações</h2></label><Textarea id="lesson-notes" placeholder="O que ficou claro? O que você ainda quer perguntar?" maxLength={10000} value={progress.notes[lesson.id]||''} onChange={e=>update({...progress,notes:{...progress.notes,[lesson.id]:e.target.value},lastLesson:lesson.id})}/><p className="muted small">As anotações são pessoais. Confira o estado de salvamento no topo.</p>{materials.some(m=>m.subject===lesson.subject)&&<><h2>Continue com a monitoria</h2><div className="resource-list">{materials.filter(m=>m.subject===lesson.subject).map(m=><a key={m.id} href={m.url} target="_blank" rel="noopener noreferrer"><span>{m.title}<small>{m.type}{monitors[m.subject]?` · ${monitors[m.subject]}`:''}</small></span><ArrowUpRight size={18}/></a>)}</div></>}<div className="source"><p>{'reference' in lesson && lesson.reference ? lesson.reference : 'Síntese didática do P.E.M a partir da ementa e dos materiais do trimestre. Use também as orientações do professor.'}</p>{'sources' in lesson && lesson.sources?.filter((source)=>/^https?:\/\//.test(source[1])).map(([label,url])=><p key={url}><a href={url} target="_blank" rel="noopener noreferrer">{label} ↗</a></p>)}</div></div></article>;
 return <><header className="page-heading"><p className="eyebrow">SEU GRIMÓRIO DE ESTUDOS</p><h1>Entender muda tudo.</h1><p>Escolha uma matéria. Leia, faça uma pausa para pensar e teste o que aprendeu.</p></header><div className="filters"><Input aria-label="Buscar assunto" placeholder="Buscar assunto: pilhas, modernismo, genética…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Matéria" value={subject} onChange={e=>setSubject(e.target.value)}><option value="">Todas as matérias</option>{subjects.map(s=><option key={s}>{s}</option>)}</select></div>{!subject&&!search&&<div className="subject-grid">{subjects.map((s,i)=><button key={s} className="subject-tile" onClick={()=>setSubject(s)}><span className="subject-no">{String(i+1).padStart(2,'0')}</span><BookOpen size={22}/><h2>{subjectName(s)}</h2><p>{lessons.filter(l=>l.subject===s).length} assuntos{monitors[s]?` · ${monitors[s]}`:''}</p><ArrowUpRight size={18}/></button>)}</div>}{(subject||search)&&<><p className="muted">{filtered.length} assuntos encontrados</p><div className="lesson-list">{filtered.map((l,i)=><button key={l.id} onClick={()=>{setLesson(l.id);update({...progress,lastLesson:l.id});}}><span className="subject-no">{String(i+1).padStart(2,'0')}</span><span><small>{subjectName(l.subject)}</small><h2>{l.title}</h2><p>{l.text[0].slice(0,120)}…</p></span>{progress.read[l.id]?<Check className="success"/>:<ArrowUpRight/>}</button>)}</div></>}</>;
}
