'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {questions,cards,subjectName,type Question} from '@/lib/content';
import type {Progress} from '@/lib/progress';
export function QuestionCard({question:q,selected,onAnswer}:{question:Question;selected?:number;onAnswer:(n:number)=>void}){return <div className="question"><p className="source">{q.source}</p><h2>{q.question}</h2><div className="options">{q.options.map((option,i)=><button key={i} disabled={selected!==undefined} className={selected!==undefined?(i===q.answer?'correct':i===selected?'wrong':''):''} onClick={()=>onAnswer(i)}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{selected!==undefined&&<div role="status" className="answer-feedback"><strong>{selected===q.answer?'Acertou.':'Vamos rever esse ponto.'}</strong><p>{q.feedback}</p></div>}</div>;}
export function Training({progress,update,bank=questions}:{progress:Progress;update:(p:Progress)=>void;bank?:Question[]}){
 const [subject,setSubject]=useState(''),[topic,setTopic]=useState(''),[index,setIndex]=useState(0),[errorsOnly,setErrors]=useState(false);
 const filtered=bank.filter(q=>(!subject||q.subject===subject)&&(!topic||q.title===topic)&&(!errorsOnly||(progress.answers[q.id]!==undefined&&progress.answers[q.id]!==q.answer)));
 const q=filtered[Math.min(index,Math.max(0,filtered.length-1))];
 return <><div className="filters"><select aria-label="Matéria das questões" value={subject} onChange={e=>{setSubject(e.target.value);setTopic('');setIndex(0);}}><option value="">Todas as matérias</option>{[...new Set(bank.map(q=>q.subject))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Assunto das questões" value={topic} onChange={e=>{setTopic(e.target.value);setIndex(0);}}><option value="">Todos os assuntos</option>{[...new Set(bank.filter(q=>!subject||q.subject===subject).map(q=>q.title))].map(s=><option key={s}>{s}</option>)}</select><Button variant={errorsOnly?'default':'outline'} onClick={()=>{setErrors(!errorsOnly);setIndex(0);}}>Caderno de erros</Button></div>{q?<><p className="eyebrow">{subjectName(q.subject)} · Questão {Math.min(index+1,filtered.length)} de {filtered.length}</p><QuestionCard question={q} selected={progress.answers[q.id]} onAnswer={a=>update({...progress,answers:{...progress.answers,[q.id]:a}})}/><div className="controls"><Button variant="outline" onClick={()=>setIndex(Math.max(0,index-1))} disabled={index===0}>Anterior</Button><Button onClick={()=>setIndex(Math.min(filtered.length-1,index+1))} disabled={index>=filtered.length-1}>Próxima questão</Button><Button variant="ghost" onClick={()=>{const answers={...progress.answers};filtered.forEach(q=>delete answers[q.id]);update({...progress,answers});setIndex(0);}}>Refazer seleção</Button></div></>:<div className="empty"><h2>{errorsOnly?'Nenhum erro registrado nessa seleção.':'Nenhuma questão encontrada.'}</h2><p>Escolha outra matéria ou volte ao treino completo.</p></div>}</>;
}
export function Flashcards(){const [subject,setSubject]=useState(''),[index,setIndex]=useState(0),[flipped,setFlipped]=useState(false);const filtered=cards.filter(c=>!subject||c[0]===subject),card=filtered[index%filtered.length];return <><div className="filters"><select aria-label="Matéria dos flashcards" value={subject} onChange={e=>{setSubject(e.target.value);setIndex(0);setFlipped(false);}}><option value="">Todas as matérias</option>{[...new Set(cards.map(c=>c[0]))].map(s=><option key={s}>{s}</option>)}</select></div><p className="eyebrow">{subjectName(card[0])} · {index%filtered.length+1}/{filtered.length}</p><button className="flashcard" onClick={()=>setFlipped(!flipped)}><span>{flipped?'RESPOSTA':'TENTE LEMBRAR'}</span><h2>{flipped?card[2]:card[1]}</h2><small>{flipped?'Clique para voltar':'Pense antes de clicar para revelar'}</small></button><div className="controls"><Button variant="outline" onClick={()=>{setIndex(Math.max(0,index-1));setFlipped(false);}}>Anterior</Button><Button onClick={()=>setFlipped(!flipped)}>{flipped?'Ver pergunta':'Revelar resposta'}</Button><Button variant="outline" onClick={()=>{setIndex(index+1);setFlipped(false);}}>Próximo</Button></div></>;}
